mysql_master:
  image: mysql:5.7
  container_name: mysql_master
  ports:
    - 3306:3306
  environment:
    - MYSQL_DATABASE=maple
    - MYSQL_USER=maple
    - MYSQL_PASSWORD=maple
    - MYSQL_ROOT_PASSWORD=QwwpugobXH5jJkw7
  volumes:
    - ./mysql_master/conf.d:/etc/mysql/conf.d
  links:
    - mysql_slave
mysql_slave:
  image: mysql:5.7
  container_name: mysql_slave
  ports:
    - 3307:3306
  environment:
    - MYSQL_DATABASE=maple
    - MYSQL_USER=maple
    - MYSQL_PASSWORD=maple
    - MYSQL_ROOT_PASSWORD=QwwpugobXH5jJkw7
  volumes:
    - ./mysql_slave/conf.d:/etc/mysql/conf.d
